version: "3.3"

services:
    app:
        container_name: "agni_app"
        build:
            context: ./app
        command:
            uvicorn app:app --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        tty: true
        volumes:
          - type: bind
            source: ./app
            target: /app
        working_dir: /app
        depends_on:
            - db

    db:
        container_name: "agni_mysql"
        build:
            context: ./database
        command:
            mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        environment:
            MYSQL_DATABASE: agni
            MYSQL_USER: agni
            MYSQL_PASSWORD: agni
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        ports:
            - 3336:3306
        volumes:
          - type: bind
            source: ./database/mysql/initdb.d
            target: /docker-entrypoint-initdb.d
          - type: bind
            source: ./database/mysql/conf.d
            target: /etc/mysql/conf.d
          - type: bind
            source: ./database/mysql/log
            target: /var/log/mysql
          - type: bind
            source: ./database/mysql/data
            target: /var/lib/mysql

