version: "3.3"

services:
    web:
        container_name: "agni_app"
        build:
            context: .
        command:
            uvicorn app:app --host 0.0.0.0 --port 8000
        restart: "always"
        tty: true
        ports:
            - 8888:8000
        volumes:
            - .:/app
        working_dir: /app

