-- -------------------------------------------------------------
-- TablePlus 4.5.0(396)
--
-- https://tableplus.com/
--
-- Database: agni
-- Generation Time: 0003-11-25 00:38:05.2250
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


INSERT INTO `search_pages` (`id`, `title`, `url`, `snippet`, `task_id`, `created_at`, `updated_at`) VALUES
(1, '針葉樹燃焼を可能にしたハイブリッド構造の薪ストーブAGNI「アグニ」-HOME-', 'http://www.nbk-okamoto.co.jp/agni/index.html', 'AGNI-HUTTEが2016グッドデザイン賞ベスト100・特別賞「ものづくりデザイン賞」を受賞しました。 創作意欲を沸き立て、美味しさを引きだす充実のクッキング機能 針葉樹燃焼も可能にしたAGNI独自のハイブリッド燃焼システム ランドスケープデザイナーによる、日本の新しいライフスタンダード Made ...', 1, '2021-11-24 23:30:53', '2021-11-24 23:30:53'),
(2, 'Agni - Wikipedia', 'https://en.wikipedia.org/wiki/Agni', 'Agni (English: / ˈ ə ɡ n i / AG-nee, Sanskrit: अग्नि, romanized: Agni) is a Sanskrit word meaning fire and connotes the fire god of Hinduism. He is also the guardian deity of the southeast direction and is typically found in southeast corners of Hindu temples. In the classical cosmology of the Indian religions, Agni as fire is one of the five inert impermanent elements ...', 1, '2021-11-24 23:26:44', '2021-11-24 23:26:44'),
(3, 'Agniの意味・使い方・読み方 | Weblio英和辞書', 'https://ejje.weblio.jp/content/Agni', 'Agni ( Sanskrit: अग्नि) is a Hindu deity, one of the most important of the Vedic gods. He is the god of fire and the acceptor of sacrifices. The sacrifices made to Agni go to the deities because Agni is a messenger from and to the other gods. He is ever-young, because the fire is re-lit every day, and also immortal.', 1, '2021-11-24 23:27:21', '2021-11-24 23:27:21'),
(4, 'Agni (missile) - Wikipedia', 'https://en.wikipedia.org/wiki/Agni_(missile)', 'The Agni missile (IAST: Agni \"Fire\") is a family of medium to intercontinental range ballistic missiles developed by India, named after one of the five elements of nature. Agni missiles are long range, nuclear weapons capable surface to surface ballistic missile. The first missile of the series, Agni-I was developed under the Integrated Guided Missile Development Program(IGMDP) and tested in 1989. After its success, …', 1, '2021-11-24 23:28:05', '2021-11-24 23:28:05'),
(5, 'Agni Systems Limited | Nationwide Data Voice & High Speed Internet', 'http://agni.com/', 'Agni Systems Limited Providing Internet access since 1995, Agni Systems Limited is an Internet Service Provider and commenced its business operation with the distinct objective of providing Internet and related services at a reasonable cost for the overall economic development of the country.', 1, '2021-11-24 23:29:01', '2021-11-24 23:29:01'),
(6, 'AGNI Online', 'https://agnionline.bu.edu/', 'AGNI Online. A literary magazine named after the Vedic fire-god. Transformative. The writer in witness, the imagination in combustion. Find out more about AGNI.', 1, '2021-11-24 23:30:01', '2021-11-24 23:30:01'),
(7, '常温ヨガ・エアリアルヨガをライフスタイルに| AGNIYOGA(アグニヨガ)三軒茶屋／新中野／高円寺／笹塚／溝の口', 'https://www.agniyoga.jp/', 'AGNI(＝浄化) によって、 女性の健康と美しさを引き出し、 イキイキと輝くライフスタイルを ご提案します。 View Concept Movie アグニヨガが選ばれる理由 豊富なレッスンプログラム 定番のハタヨガ、アロマヨガ、姿勢調整ヨガなどから ...', 1, '2021-11-24 23:30:01', '2021-11-24 23:30:01'),
(8, 'Agni - World History Encyclopedia', 'https://www.worldhistory.org/Agni/', 'Agni is the Hindu god of fire. He is regarded as the friend and protector of humanity, in particular, he safeguards the home. Various forms of fire are associated with Agni and include the sun, lightning, comets, sacrificial fire, domestic fires, the fire of the funeral pyre, and the digestive fire which is within all humans.', 1, '2021-11-24 23:33:43', '2021-11-24 23:33:43'),
(9, 'Agni: the Fire God of the Hindus - Learn Religions', 'https://www.learnreligions.com/agni-the-fire-god-1770291', 'Agni, the god of Fire, is one of the most prominent of the deities of the Vedas.With the single exception of Indra, more hymns are addressed to Angi than to any other deity. To this day, Agni forms a part of many rites-of', 1, '2021-11-24 23:34:27', '2021-11-24 23:34:27'),
(10, 'The Importance of Agni - Ayurveda | Banyan Botanicals', 'https://www.banyanbotanicals.com/info/ayurvedic-living/living-ayurveda/health-guides/understanding-agni/the-importance-of-agni/', 'The Importance of Agni. The Ayurvedic concept of fire, or agni, is critically important to our overall health. Agni is the force of intelligence within each cell, each tissue, and every system within the body. Ultimately, it is the discernment of agni that determines which substances enter our cells and tissues, and which substances should be ...', 1, '2021-11-24 23:34:59', '2021-11-24 23:34:59'),
(11, '針葉樹燃焼を可能にしたハイブリッド構造の薪ストーブAGNI「アグニ」-HOME-', 'http://www.nbk-okamoto.co.jp/agni/index.html', 'AGNI-HUTTEが2016グッドデザイン賞ベスト100・特別賞「ものづくりデザイン賞」を受賞しました。 創作意欲を沸き立て、美味しさを引きだす充実のクッキング機能 針葉樹燃焼も可能にしたAGNI独自のハイブリッド燃焼システム ランドスケープデザイナーによる、日本の新しいライフスタンダード Made ...', 2, '2021-11-24 23:30:53', '2021-11-24 23:30:53'),
(12, 'Agni - Wikipedia', 'https://en.wikipedia.org/wiki/Agni', 'Agni (English: / ˈ ə ɡ n i / AG-nee, Sanskrit: अग्नि, romanized: Agni) is a Sanskrit word meaning fire and connotes the fire god of Hinduism. He is also the guardian deity of the southeast direction and is typically found in southeast corners of Hindu temples. In the classical cosmology of the Indian religions, Agni as fire is one of the five inert impermanent elements ...', 2, '2021-11-24 23:26:44', '2021-11-24 23:26:44'),
(13, 'Agniの意味・使い方・読み方 | Weblio英和辞書', 'https://ejje.weblio.jp/content/Agni', 'Agni ( Sanskrit: अग्नि) is a Hindu deity, one of the most important of the Vedic gods. He is the god of fire and the acceptor of sacrifices. The sacrifices made to Agni go to the deities because Agni is a messenger from and to the other gods. He is ever-young, because the fire is re-lit every day, and also immortal.', 2, '2021-11-24 23:27:21', '2021-11-24 23:27:21'),
(14, 'Agni (missile) - Wikipedia', 'https://en.wikipedia.org/wiki/Agni_(missile)', 'The Agni missile (IAST: Agni \"Fire\") is a family of medium to intercontinental range ballistic missiles developed by India, named after one of the five elements of nature. Agni missiles are long range, nuclear weapons capable surface to surface ballistic missile. The first missile of the series, Agni-I was developed under the Integrated Guided Missile Development Program(IGMDP) and tested in 1989. After its success, …', 2, '2021-11-24 23:28:05', '2021-11-24 23:28:05'),
(15, 'Agni Systems Limited | Nationwide Data Voice & High Speed Internet', 'http://agni.com/', 'Agni Systems Limited Providing Internet access since 1995, Agni Systems Limited is an Internet Service Provider and commenced its business operation with the distinct objective of providing Internet and related services at a reasonable cost for the overall economic development of the country.', 2, '2021-11-24 23:29:01', '2021-11-24 23:29:01'),
(16, 'AGNI Online', 'https://agnionline.bu.edu/', 'AGNI Online. A literary magazine named after the Vedic fire-god. Transformative. The writer in witness, the imagination in combustion. Find out more about AGNI.', 2, '2021-11-24 23:30:01', '2021-11-24 23:30:01'),
(17, '常温ヨガ・エアリアルヨガをライフスタイルに| AGNIYOGA(アグニヨガ)三軒茶屋／新中野／高円寺／笹塚／溝の口', 'https://www.agniyoga.jp/', 'AGNI(＝浄化) によって、 女性の健康と美しさを引き出し、 イキイキと輝くライフスタイルを ご提案します。 View Concept Movie アグニヨガが選ばれる理由 豊富なレッスンプログラム 定番のハタヨガ、アロマヨガ、姿勢調整ヨガなどから ...', 2, '2021-11-24 23:30:01', '2021-11-24 23:30:01'),
(18, 'Agni - World History Encyclopedia', 'https://www.worldhistory.org/Agni/', 'Agni is the Hindu god of fire. He is regarded as the friend and protector of humanity, in particular, he safeguards the home. Various forms of fire are associated with Agni and include the sun, lightning, comets, sacrificial fire, domestic fires, the fire of the funeral pyre, and the digestive fire which is within all humans.', 2, '2021-11-24 23:33:43', '2021-11-24 23:33:43'),
(19, 'Agni: the Fire God of the Hindus - Learn Religions', 'https://www.learnreligions.com/agni-the-fire-god-1770291', 'Agni, the god of Fire, is one of the most prominent of the deities of the Vedas.With the single exception of Indra, more hymns are addressed to Angi than to any other deity. To this day, Agni forms a part of many rites-of', 2, '2021-11-24 23:34:27', '2021-11-24 23:34:27'),
(20, 'The Importance of Agni - Ayurveda | Banyan Botanicals', 'https://www.banyanbotanicals.com/info/ayurvedic-living/living-ayurveda/health-guides/understanding-agni/the-importance-of-agni/', 'The Importance of Agni. The Ayurvedic concept of fire, or agni, is critically important to our overall health. Agni is the force of intelligence within each cell, each tissue, and every system within the body. Ultimately, it is the discernment of agni that determines which substances enter our cells and tissues, and which substances should be ...', 2, '2021-11-24 23:34:59', '2021-11-24 23:34:59'),
(21, '針葉樹燃焼を可能にしたハイブリッド構造の薪ストーブAGNI「アグニ」-HOME-', 'http://www.nbk-okamoto.co.jp/agni/index.html', 'AGNI-HUTTEが2016グッドデザイン賞ベスト100・特別賞「ものづくりデザイン賞」を受賞しました。 創作意欲を沸き立て、美味しさを引きだす充実のクッキング機能 針葉樹燃焼も可能にしたAGNI独自のハイブリッド燃焼システム ランドスケープデザイナーによる、日本の新しいライフスタンダード Made ...', 3, '2021-11-24 23:30:53', '2021-11-24 23:30:53'),
(22, 'Agni - Wikipedia', 'https://en.wikipedia.org/wiki/Agni', 'Agni (English: / ˈ ə ɡ n i / AG-nee, Sanskrit: अग्नि, romanized: Agni) is a Sanskrit word meaning fire and connotes the fire god of Hinduism. He is also the guardian deity of the southeast direction and is typically found in southeast corners of Hindu temples. In the classical cosmology of the Indian religions, Agni as fire is one of the five inert impermanent elements ...', 3, '2021-11-24 23:26:44', '2021-11-24 23:26:44'),
(23, 'Agniの意味・使い方・読み方 | Weblio英和辞書', 'https://ejje.weblio.jp/content/Agni', 'Agni ( Sanskrit: अग्नि) is a Hindu deity, one of the most important of the Vedic gods. He is the god of fire and the acceptor of sacrifices. The sacrifices made to Agni go to the deities because Agni is a messenger from and to the other gods. He is ever-young, because the fire is re-lit every day, and also immortal.', 3, '2021-11-24 23:27:21', '2021-11-24 23:27:21'),
(24, 'Agni (missile) - Wikipedia', 'https://en.wikipedia.org/wiki/Agni_(missile)', 'The Agni missile (IAST: Agni \"Fire\") is a family of medium to intercontinental range ballistic missiles developed by India, named after one of the five elements of nature. Agni missiles are long range, nuclear weapons capable surface to surface ballistic missile. The first missile of the series, Agni-I was developed under the Integrated Guided Missile Development Program(IGMDP) and tested in 1989. After its success, …', 3, '2021-11-24 23:28:05', '2021-11-24 23:28:05'),
(25, 'Agni Systems Limited | Nationwide Data Voice & High Speed Internet', 'http://agni.com/', 'Agni Systems Limited Providing Internet access since 1995, Agni Systems Limited is an Internet Service Provider and commenced its business operation with the distinct objective of providing Internet and related services at a reasonable cost for the overall economic development of the country.', 3, '2021-11-24 23:29:01', '2021-11-24 23:29:01'),
(26, 'AGNI Online', 'https://agnionline.bu.edu/', 'AGNI Online. A literary magazine named after the Vedic fire-god. Transformative. The writer in witness, the imagination in combustion. Find out more about AGNI.', 3, '2021-11-24 23:30:01', '2021-11-24 23:30:01'),
(27, '常温ヨガ・エアリアルヨガをライフスタイルに| AGNIYOGA(アグニヨガ)三軒茶屋／新中野／高円寺／笹塚／溝の口', 'https://www.agniyoga.jp/', 'AGNI(＝浄化) によって、 女性の健康と美しさを引き出し、 イキイキと輝くライフスタイルを ご提案します。 View Concept Movie アグニヨガが選ばれる理由 豊富なレッスンプログラム 定番のハタヨガ、アロマヨガ、姿勢調整ヨガなどから ...', 3, '2021-11-24 23:30:01', '2021-11-24 23:30:01'),
(28, 'Agni - World History Encyclopedia', 'https://www.worldhistory.org/Agni/', 'Agni is the Hindu god of fire. He is regarded as the friend and protector of humanity, in particular, he safeguards the home. Various forms of fire are associated with Agni and include the sun, lightning, comets, sacrificial fire, domestic fires, the fire of the funeral pyre, and the digestive fire which is within all humans.', 3, '2021-11-24 23:33:43', '2021-11-24 23:33:43'),
(29, 'Agni: the Fire God of the Hindus - Learn Religions', 'https://www.learnreligions.com/agni-the-fire-god-1770291', 'Agni, the god of Fire, is one of the most prominent of the deities of the Vedas.With the single exception of Indra, more hymns are addressed to Angi than to any other deity. To this day, Agni forms a part of many rites-of', 3, '2021-11-24 23:34:27', '2021-11-24 23:34:27'),
(30, 'The Importance of Agni - Ayurveda | Banyan Botanicals', 'https://www.banyanbotanicals.com/info/ayurvedic-living/living-ayurveda/health-guides/understanding-agni/the-importance-of-agni/', 'The Importance of Agni. The Ayurvedic concept of fire, or agni, is critically important to our overall health. Agni is the force of intelligence within each cell, each tissue, and every system within the body. Ultimately, it is the discernment of agni that determines which substances enter our cells and tissues, and which substances should be ...', 3, '2021-11-24 23:34:59', '2021-11-24 23:34:59'),
(31, '針葉樹燃焼を可能にしたハイブリッド構造の薪ストーブAGNI「アグニ」-HOME-', 'http://www.nbk-okamoto.co.jp/agni/index.html', 'AGNI-HUTTEが2016グッドデザイン賞ベスト100・特別賞「ものづくりデザイン賞」を受賞しました。 創作意欲を沸き立て、美味しさを引きだす充実のクッキング機能 針葉樹燃焼も可能にしたAGNI独自のハイブリッド燃焼システム ランドスケープデザイナーによる、日本の新しいライフスタンダード Made ...', 4, '2021-11-24 23:30:53', '2021-11-24 23:30:53'),
(32, 'Agni - Wikipedia', 'https://en.wikipedia.org/wiki/Agni', 'Agni (English: / ˈ ə ɡ n i / AG-nee, Sanskrit: अग्नि, romanized: Agni) is a Sanskrit word meaning fire and connotes the fire god of Hinduism. He is also the guardian deity of the southeast direction and is typically found in southeast corners of Hindu temples. In the classical cosmology of the Indian religions, Agni as fire is one of the five inert impermanent elements ...', 4, '2021-11-24 23:26:44', '2021-11-24 23:26:44'),
(33, 'Agniの意味・使い方・読み方 | Weblio英和辞書', 'https://ejje.weblio.jp/content/Agni', 'Agni ( Sanskrit: अग्नि) is a Hindu deity, one of the most important of the Vedic gods. He is the god of fire and the acceptor of sacrifices. The sacrifices made to Agni go to the deities because Agni is a messenger from and to the other gods. He is ever-young, because the fire is re-lit every day, and also immortal.', 4, '2021-11-24 23:27:21', '2021-11-24 23:27:21'),
(34, 'Agni (missile) - Wikipedia', 'https://en.wikipedia.org/wiki/Agni_(missile)', 'The Agni missile (IAST: Agni \"Fire\") is a family of medium to intercontinental range ballistic missiles developed by India, named after one of the five elements of nature. Agni missiles are long range, nuclear weapons capable surface to surface ballistic missile. The first missile of the series, Agni-I was developed under the Integrated Guided Missile Development Program(IGMDP) and tested in 1989. After its success, …', 4, '2021-11-24 23:28:05', '2021-11-24 23:28:05'),
(35, 'Agni Systems Limited | Nationwide Data Voice & High Speed Internet', 'http://agni.com/', 'Agni Systems Limited Providing Internet access since 1995, Agni Systems Limited is an Internet Service Provider and commenced its business operation with the distinct objective of providing Internet and related services at a reasonable cost for the overall economic development of the country.', 4, '2021-11-24 23:29:01', '2021-11-24 23:29:01'),
(36, 'AGNI Online', 'https://agnionline.bu.edu/', 'AGNI Online. A literary magazine named after the Vedic fire-god. Transformative. The writer in witness, the imagination in combustion. Find out more about AGNI.', 4, '2021-11-24 23:30:01', '2021-11-24 23:30:01'),
(37, '常温ヨガ・エアリアルヨガをライフスタイルに| AGNIYOGA(アグニヨガ)三軒茶屋／新中野／高円寺／笹塚／溝の口', 'https://www.agniyoga.jp/', 'AGNI(＝浄化) によって、 女性の健康と美しさを引き出し、 イキイキと輝くライフスタイルを ご提案します。 View Concept Movie アグニヨガが選ばれる理由 豊富なレッスンプログラム 定番のハタヨガ、アロマヨガ、姿勢調整ヨガなどから ...', 4, '2021-11-24 23:30:01', '2021-11-24 23:30:01'),
(38, 'Agni - World History Encyclopedia', 'https://www.worldhistory.org/Agni/', 'Agni is the Hindu god of fire. He is regarded as the friend and protector of humanity, in particular, he safeguards the home. Various forms of fire are associated with Agni and include the sun, lightning, comets, sacrificial fire, domestic fires, the fire of the funeral pyre, and the digestive fire which is within all humans.', 4, '2021-11-24 23:33:43', '2021-11-24 23:33:43'),
(39, 'Agni: the Fire God of the Hindus - Learn Religions', 'https://www.learnreligions.com/agni-the-fire-god-1770291', 'Agni, the god of Fire, is one of the most prominent of the deities of the Vedas.With the single exception of Indra, more hymns are addressed to Angi than to any other deity. To this day, Agni forms a part of many rites-of', 4, '2021-11-24 23:34:27', '2021-11-24 23:34:27'),
(40, 'The Importance of Agni - Ayurveda | Banyan Botanicals', 'https://www.banyanbotanicals.com/info/ayurvedic-living/living-ayurveda/health-guides/understanding-agni/the-importance-of-agni/', 'The Importance of Agni. The Ayurvedic concept of fire, or agni, is critically important to our overall health. Agni is the force of intelligence within each cell, each tissue, and every system within the body. Ultimately, it is the discernment of agni that determines which substances enter our cells and tissues, and which substances should be ...', 4, '2021-11-24 23:34:59', '2021-11-24 23:34:59');


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;